### Creation of Array


In [2]:
my_list=[1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [3]:
import numpy as np

In [4]:
array=np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [5]:
array=array.reshape(3,2)
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
array.shape


(3, 2)

In [7]:
array = array.reshape(1,-1)
array

array([[1, 2, 3, 4, 5, 6]])

In [8]:
type(array)

numpy.ndarray

In [9]:
array.ndim

2

In [10]:
array=array.reshape(3,1,-1)
array

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [11]:
array.ndim


3

In [12]:
lst1=[1,2,3,4,5,6]
lst2=[6,5,4,3,2,1]
lst3=[2,4,6,7,8,9]
mul_arr=np.array([lst1,lst2,lst3])
print(mul_arr)

print(mul_arr.shape)
mul_arr.ndim

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [2 4 6 7 8 9]]
(3, 6)


2

In [13]:
mul_arr.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1, 2, 4, 6, 7, 8, 9]])

In [14]:
a=np.arange(0,24)
print(*a)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23


## Mathematical Operatons on Numpy Arrays 

In [24]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
x,y

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [26]:
# nump.add()
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [27]:
#numpy.subtract()
print(y-x)
print(np.subtract(x,y))

[[4 4]
 [4 4]]
[[-4 -4]
 [-4 -4]]


In [28]:
#element wise multiplication 
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [29]:
#dot produts of 2 arrays
print(x.dot(y))

[[19 22]
 [43 50]]


In [32]:
#element wise division
print(y/x)

[[5.         3.        ]
 [2.33333333 2.        ]]


In [35]:
print(np.sum(x))

10


In [38]:
print(np.sum(x,axis=1))
print(np.sum(x,axis=0))
# axis =0 performs operation on col
# axis=1 performs operation on rows

[3 7]
[4 6]


In [41]:
lst="occurence"
a=[x for x in lst if lst.index(x)%3==0]
print(*a)

o u n
