### Creation of Array


In [1]:
my_list=[1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [2]:
import numpy as np

In [3]:
array=np.array(my_list,dtype=int)
print(array)

[1 2 3 4 5 6]


In [10]:
array=array.reshape(3,2)
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
array.shape


(3, 2)

In [14]:
array = array.reshape(1,-1)
array

array([[1, 2, 3, 4, 5, 6]])

In [15]:
type(array)

numpy.ndarray

In [16]:
array.ndim

2

In [18]:
array=array.reshape(3,1,-1)
array

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [19]:
array.ndim


3

In [22]:
lst1=[1,2,3,4,5,6]
lst2=[6,5,4,3,2,1]
lst3=[2,4,6,7,8,9]
mul_arr=np.array([lst1,lst2,lst3])
print(mul_arr)

print(mul_arr.shape)
mul_arr.ndim

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]
 [2 4 6 7 8 9]]
(3, 6)


2

In [25]:
mul_arr.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 6, 5, 4, 3, 2, 1, 2, 4, 6, 7, 8, 9]])

In [29]:
a=np.arange(0,24)
print(*a)

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23


## Mathematical Operatons on Numpy Arrays 